// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_z9g9KdnjzJ-wlDPwDlPZKFmPTR7pqA',
    appId: '1:583093229435:web:e7c358466b05be23688fde',
    messagingSenderId: '583093229435',
    projectId: 'flutter-project-ba8bc',
    authDomain: 'flutter-project-ba8bc.firebaseapp.com',
    storageBucket: 'flutter-project-ba8bc.appspot.com',
    measurementId: 'G-6LE0WSS9HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9jnTlfBU4AZc674a5em4QfEWrCOELW4',
    appId: '1:583093229435:android:a4d32845d1c6951a688fde',
    messagingSenderId: '583093229435',
    projectId: 'flutter-project-ba8bc',
    storageBucket: 'flutter-project-ba8bc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI_z9g9KdnjzJ-wlDPwDlPZKFmPTR7pqA',
    appId: '1:583093229435:web:5ed7b510c2951217688fde',
    messagingSenderId: '583093229435',
    projectId: 'flutter-project-ba8bc',
    authDomain: 'flutter-project-ba8bc.firebaseapp.com',
    storageBucket: 'flutter-project-ba8bc.appspot.com',
    measurementId: 'G-7HXQBWD8V7',
  );
}
